{% set name = "fixit" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fixit-{{ version }}.tar.gz
  sha256: b31665cb6491d659d8dfef5a6078a7e9f786e299826636d03d6bd91b6f71e95b

build:
  entry_points:
    - fixit = fixit.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.0
    - libcst >=0.3.18
    - moreorless >=0.4.0
    - packaging >=21
    - tomli >=2.0
    - trailrunner >=1.2

test:
  imports:
    - fixit
  commands:
    - pip check
    - fixit --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Instagram/Fixit
  summary: A lint framework that writes better Python code for you.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
